name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o main.bin cmd/main.go

    - name: Test
      run: go test -v ./...

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: main.bin
        path: main.bin
        retention-days: 5

  docker:
    name: Create Docker Container
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: main.bin
      - shell: bash
        run: |
          ./main.bin

