name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o main.bin cmd/main.go

    - name: Test
      run: go test -v ./...

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: main.bin
        path: main.bin
        retention-days: 5

  docker:
    name: Create Docker Container
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: main.bin
      - shell: bash
        run: |
          chmod +x ./main.bin
          ./main.bin
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: diegodev/test:latest

